# Generated by Django 5.0.1 on 2024-01-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('kind', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15)),
                ('max_size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
